services:
  apigateway:
    image: spacestalinnn/apigateway:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
       - "8080:80"
    environment:
        - ASPNETCORE_URLS=http://+:80       
        - ASPNETCORE_ENVIRONMENT=Development
  chatbot:
    image: spacestalinnn/chatbot-service:latest
    build:
      context: ../ChatbotService
      dockerfile: ../ChatbotService/src/API/Dockerfile
    ports:
       - "5001:80"
    environment:
       - ASPNETCORE_URLS=http://+:80        
       - ASPNETCORE_ENVIRONMENT=Development
  user:
    image: spacestalinnn/user-service:latest
    build:
      context: ../UserService
      dockerfile: ../UserService/src/API/Dockerfile
    ports:
       - "5002:80"
    environment:
       - ASPNETCORE_URLS=http://+:80  
       - ASPNETCORE_ENVIRONMENT=Development
  knowledgebase:
    image: spacestalinnn/knowledgebase-service:latest
    build:
      context: ../KnowledgeBaseService
      dockerfile: ../KnowledgeBaseService/src/API/Dockerfile
    ports:
       - "5003:80"
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ASPNETCORE_URLS=http://+:80