version: '3.8'

services:
  apigateway:
    image: spacestalinnn/apigateway:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_URLS=http://+:80    
    depends_on:
      - user
      - lead
      - college

  rabbitmq-app:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"

  user:
    image: spacestalinnn/user-service:latest
    build:
      context: ./UserService 
      dockerfile: src/API/Dockerfile 
    ports:
      - "5002:80"
    environment:
      - RABBITMQ_URI=amqp://user:4664lythihonG*@rabbitmq-app:5672/%2f
      - ASPNETCORE_URLS=http://+:80  
      - Jwt__SecretKey=u8Qw1v9k2l5s8x/AeD3G6j9L2p4s7v0yB1e4h7k0n3r6u9z/C5F8J2M5Q8T1W4Z7
      - Jwt__Issuer=BE_UserService
      - Jwt__Audience=FE
      - Jwt__AccessTokenExpirationMinutes=60
      - Jwt__RefreshTokenExpirationDays=7
      - Email__From=251qbao@gmail.com
      - Email__SmtpHost=smtp.gmail.com
      - Email__SmtpPort=465
      - Email__Username=251qbao@gmail.com
      - Email__Password=bydi vpbd hyiz fjtq
      - Email__ConfirmationBaseUrl=http://localhost:5002

  lead:
    image: spacestalinnn/lead-service:latest
    build:
      context: ./LeadManagementService
      dockerfile: src/API/Dockerfile
    ports:
      - "5012:80"
    environment:
      - RABBITMQ_URI=amqp://user:4664lythihonG*@rabbitmq-app:5672/%2f
      - ASPNETCORE_URLS=http://+:80

  college:
    image: spacestalinnn/collegeinfo-service:latest
    build:
      context: ./CollegeInfoService
      dockerfile: src/API/Dockerfile
    ports:
      - "5010:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
